### PR TITLE
[MIG] l10n_fi_business_code: Migration to 13.0

### PR DESCRIPTION
**Pull request by Menestrels**
Related task: https://odoo.web-veistamo.fi/web#id=12763&view_type=form&model=project.task&menu_id=192&action=201

### CODE REVIEW

**Review by mlaitinen — CHANGES_REQUESTED** [review]
This module depends on `partner_identification` which isn't available. In `oca_dependencies.txt` the OCA repository `partner-contact` is defined, but it can't work for two reasons:

1. The branch isn't defined, so it most likely defaults to the same branch as where `l10n-finland` is. Since OCA doesn't have a `13.0-avsy` branch, this can't possibly work.
2. Even if the branch was `13.0`, the `partner_identification` module is not available in the OCA repository.

Where's the working version of `partner_identification`?

**Comment by Menestrels** [comment]
@mlaitinen Right, `partner_identification` dependency. It's stuck in an open pull request: https://github.com/OCA/partner-contact/pull/815

I'm not sure whats the best course of action here. Create new branch in avoinsystems/partner-contact 13-avsy and merge module there? God knows how long it will take for the module to get merged in OCA/partner-contact repo.

**Comment by mlaitinen** [comment]
You can add 
```
partner-contact https://github.com/avoinsystems/partner-contact 13.0-avoinsystems
``` 
into `oca_dependencies.txt`

**Comment by Menestrels** [comment]
@mlaitinen I added  `oca_dependencies.txt`

**Review by mlaitinen — APPROVED** [review]

**Pull request merged**
